### ISSUE TITLE
Failed to find parent entity when launching dolly_ignition demo

### ISSUE THREAD

**Issue by ruffsl** [chapulina/dolly#24] opened 2020-09-19 02:37 UTC
Looks like the gzclient immediately crashes upon launching the dolly_gazebo demo.
To reproduce: see the rocker command below using the Docker image from https://github.com/chapulina/dolly/pull/22 .

### dolly_ignition

<details>

```
$ rocker --nvidia --x11 --net=host --pulse chapulina/dolly:foxy
# ros2 launch dolly_ignition dolly.launch.py
[INFO] [launch]: All log files can be found below /root/.ros/log/2020-09-18-19-21-35-443059-cog-rw07-48
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ign gazebo-1]: process started with pid [50]
[INFO] [create-2]: process started with pid [52]
[INFO] [dolly_follow-3]: process started with pid [54]
[INFO] [parameter_bridge-4]: process started with pid [57]
[INFO] [rviz2-5]: process started with pid [59]
[create-2] [INFO] [1600482095.605943749] [ros_ign_gazebo]: Requesting list of world names.
[rviz2-5] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[ign gazebo-1] [Wrn] [URI.cc:580] Unable to parse URI [/opt/overlay_ws/install/dolly_ignition/share/dolly_ignition/worlds/station.sdf]. Ignoring.
[ign gazebo-1] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[ign gazebo-1] [Wrn] [LocalCache.cc:102] Server directory does not exist [/root/.ignition/fuel/fuel.ignitionrobotics.org]
[rviz2-5] [INFO] [1600482096.575192993] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-5] [INFO] [1600482096.575321441] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
[rviz2-5] [INFO] [1600482096.708767961] [rviz2]: Stereo is NOT SUPPORTED
[create-2] [INFO] [1600482098.507048591] [ros_ign_gazebo]: Requested creation of entity.
[create-2] [INFO] [1600482098.507129514] [ros_ign_gazebo]: OK creation of entity.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
[INFO] [create-2]: process has finished cleanly [pid 52]
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/WorldControl/WorldControl.qml:88:3: QML RoundButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/WorldControl/WorldControl.qml:88:3: QML RoundButton: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [Wrn] [Component.hh:144] Trying to serialize component with data type [N3sdf2v95WorldE], which doesn't have `operator<<`. Component will not be serialized.
[ign gazebo-1] [Wrn] [Component.hh:144] Trying to serialize component with data type [N3sdf2v95ModelE], which doesn't have `operator<<`. Component will not be serialized.
[ign gazebo-1] Warning [parser.cc:866] XML Attribute[frame] in element[pose] not defined in SDF, ignoring.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[parameter_bridge-4] [INFO] [1600482102.909747661] [ros_ign_bridge]: Passing message from ROS sensor_msgs/msg/LaserScan to Ignition ignition.msgs.LaserScan (showing msg only once per type
[parameter_bridge-4] [INFO] [1600482102.910267952] [ros_ign_bridge]: Passing message from ROS geometry_msgs/msg/Twist to Ignition ignition.msgs.Twist (showing msg only once per type
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [12]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [13]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [13]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [13]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [17]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [17]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [20]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [20]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [23]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [23]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [26]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [12]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [12]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [12]
[ign gazebo-1] [GUI] [Err] [EntityTree.cc:128] Failed to find parent entity [12]
[parameter_bridge-4] [INFO] [1600482109.454707833] [ros_ign_bridge]: Passing message from ROS nav_msgs/msg/Odometry to Ignition ignition.msgs.Odometry (showing msg only once per type
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[rviz2-5] [INFO] [1600482118.464797090] [rclcpp]: signal_handler(signal_value=2)
[parameter_bridge-4] [INFO] [1600482118.464812578] [rclcpp]: signal_handler(signal_value=2)
[dolly_follow-3] [INFO] [1600482118.464821221] [rclcpp]: signal_handler(signal_value=2)
[INFO] [dolly_follow-3]: process has finished cleanly [pid 54]
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[ign gazebo-1] [GUI] [Wrn] [Application.cc:649] [QT] file::/ComponentInspector/Vector3d.qml:93:9: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
[INFO] [rviz2-5]: process has finished cleanly [pid 59]
[ERROR] [ign gazebo-1]: process has died [pid 50, exit code -2, cmd 'ign gazebo /opt/overlay_ws/install/dolly_ignition/share/dolly_ignition/worlds/station.sdf -v 2 --gui-config /opt/overlay_ws/install/dolly_ignition/share/dolly_ignition/ign/gui.config'].
[ERROR] [parameter_bridge-4]: process[parameter_bridge-4] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [parameter_bridge-4]: sending signal 'SIGTERM' to process[parameter_bridge-4]
[INFO] [parameter_bridge-4]: process has finished cleanly [pid 57]
```

**Comment by ruffsl** [comment] 2020-09-19 02:43
After a consecutive rerun in the same container, it seems to be working now.

![image](https://user-images.githubusercontent.com/2293573/93657759-fc12ad00-f9e9-11ea-9585-7ce0d63f57ad.png)

My guess: loading the model timed out, or an initial download from an online resource was required upon initial startup of ignition?

**Comment by chapulina** [comment] 2020-09-19 18:27
I'm having the same issue as https://github.com/chapulina/dolly/issues/23#issuecomment-695340571 with the provided docker file. I believe the issue is in the Docker setup, not the packages.

```
/opt/overlay_ws# ign gazebo -v 4 -g
[Msg] Ignition Gazebo GUI    v3.3.0
No protocol specified
qt.qpa.xcb: could not connect to display :1
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```

**Comment by chapulina** [comment] 2021-09-06 18:25
I just tried reproducing this now 1 year later and I can't, so closing!

**Closed as completed by chapulina** 2021-09-06 18:25 UTC
Labels: invalid, ignition
