### ISSUE TITLE
Unable to visualize lidar ray on the rviz

### ISSUE THREAD

**Issue by fairuskhalid** [chapulina/dolly#16] opened 2020-07-27 01:30 UTC
Hi, I am trying out your dolly demo:

ros2 launch dolly_ignition dolly.launch.py

Everything load successfully. I can see the graphic on gazebo. I can see rviz received the message but I can't see the lidar ray on the rviz.

```
ubuntu@ubuntu-OptiPlex-7070:~$ ros2 topic list
/clicked_point
/dolly/cmd_vel
/dolly/laser_scan
/dolly/odometry
/initialpose
/move_base_simple/goal
/parameter_events
/rosout
/tf
/tf_static
```

```
ubuntu@ubuntu-OptiPlex-7070:~$ ros2 topic echo /dolly/laser_scan
header:
  stamp:
    sec: 113
    nanosec: 790000000
  frame_id: dolly/chassis/sensor_ray
angle_min: -1.0
angle_max: 1.0
angle_increment: 0.01005025114864111
time_increment: 0.0
scan_time: 0.0
range_min: 0.05000000074505806
range_max: 10.0
ranges: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, '...']
intensities: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, '...']
```

**Comment by chapulina** [comment] 2020-07-27 15:57
Hi @fairuskhalid , maybe the point cloud is there, but it's hard to see? You can try making the `LaserScan` display size very large on the left panel on RViz. Set the `Size (m)` to something huge like 1 meter. Also make sure that the `Status` says that there are messages received.

Finally, make sure there's something in front of Dolly so the laser scans are hitting something.

**Comment by fairuskhalid** [comment] 2020-07-28 14:57
Thanks for the response.  I tried your suggestion but still I don't see anything on the rviz window. just to share with you I tried:

ros2 launch dummy_robot_bringup dummy_robot_bringup.launch.py

and run rviz with 0.01 size I can see the laser scan.

my system:
OS - Ubuntu 18.04
ROS -Eloquent
RVIZ - version Alpha (ROS 2.0), compiled against Qt version 5.9.5, compiled against OGRE version 1.12.1

**Comment by olmerg** [comment] 2020-07-31 15:23
I have the same problem with ros foxy, i can read the lidar topic in through cli but it does not work in rviz or rqt.

- it is ok :Read the topic through using ``ros2 topic echo /dolly/idar``
- do not work: add the plugin laser_scan in rviz2
- do not work: view the topic through topic monitor in rqt

The same is happening in other sensor of ros gazebo_pkg like likelibgazebo_ros_gps_sensor or libgazebo_ros_p3d, but it did not happen with libgazebo_ros_joint_state_publisher or libgazebo_ros_diff_drive.

I have tested to configure use_sim_time in rqt or rviz but ir does not solve the problem. 

my system:
OS Ubuntu 20.04
ROS- foxy (updated)
all packages from apt-get

**Comment by olmerg** [comment] 2020-07-31 15:53
I think that the problem is the qos in the plugins because the plugins that works does not use rclcpp::SensorDataQoS , but my knowlegde abut ros2 is beginner level(nothing about QoS).

https://github.com/ros-simulation/gazebo_ros_pkgs/blob/ros2/gazebo_plugins/src/gazebo_ros_p3d.cpp#L123
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/ros2/gazebo_plugins/src/gazebo_ros_ray_sensor.cpp#L110

and the plugins that works:
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/ros2/gazebo_plugins/src/gazebo_ros_p3d.cpp#L123
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/ros2/gazebo_plugins/src/gazebo_ros_joint_state_publisher.cpp#L142



I assume this by this thread https://answers.ros.org/question/332207/cant-receive-data-in-python-node/

**Comment by chapulina** [comment] 2020-08-15 16:53
## dolly_ignition

I can't reproduce this issue with `dolly_ignition`, probably because `ros_ign` is using default QoS settings to publish the sensor data. No matter how I change the QoS options on RViz (the ones under `LaserScan` :arrow_right: `Topic`), I can't get in a situation where the data is not visible.

@fairuskhalid's original report seemed to be using `dolly_ignition` - can you confirm that your problem is indeed happening with that package?

## dolly_gazebo

For `dolly_gazebo`, @olmerg is probably right that the issue is related to QoS settings. If you use the RViz configuration that's installed with the package, the sensor data is visible:

https://github.com/chapulina/dolly/blob/349c35288b3a78a66249a1eef66bd507a0fed750/dolly_gazebo/rviz/dolly_gazebo.rviz#L71-L76

But if you're inserting the `LaserScan` manually, the default QoS settings will not work, because it uses `Reliable`. So you need to change the `Reliability Policy` from `Reliable` to `Best Effort` or `System Default`. This works for me.

**Comment by olmerg** [comment] 2020-08-17 13:24
Dear chapulina, 

It works great, thanks.
I have changed this policy at rviz in run time but It did not work, but after I save in the config file it work great.

**Comment by jediofgever** [comment] 2020-08-31 01:30
After changing Reliability Policy from Reliable to any other two options I was able to visualize lidar data. But for camera image I am still unable to visualize image

**Comment by chapulina** [comment] 2020-09-19 21:30
> But for camera image I am still unable to visualize image

@jediofgever , could you ticket a new issue explaining your problem? Or, if you're not sure it's a bug, please ask a question at https://answers.gazebosim.org/. 

---

It sounds like the lidar issue is resolved choosing the correct QoS settings on RViz, so I'll close this issue :v:

**Closed as completed by chapulina** 2020-09-19 21:30 UTC

**Comment by jediofgever** [comment] 2020-09-21 05:42
Thanks @chapulina . I think my problem is related to something related to RVIZ itself. There is an already open issue there, which we hope will be looked after. https://github.com/ros2/rviz/issues/575
